# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[plugins]
# Core
"rocks.nvim" = "2.35.2"
"rocks-git.nvim" = "2.0.0"
"rocks-config.nvim" = "2.1.4"

# Themes
"gruvbox.nvim" = "2.0.0"
"monokai.nvim" = "scm"
"nightfox.nvim" = "3.9.3"

# General
"which-key.nvim" = "3.4.0"
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim" }
"lualine.nvim" = "scm"
"toggleterm.nvim" = "2.11.0"
nvim-surround = "2.1.5"
"indent-blankline.nvim" = "3.7.1"
"comment.nvim" = "0.8.0"
"eyeliner.nvim" = { git = "jinh0/eyeliner.nvim" }

# Telescope
"telescope.nvim" = "scm"
"telescope-ui-select.nvim" = "scm"
"telescope-fzf-native.nvim" = "scm"

# Lsp
nvim-lspconfig = "0.1.8"
"mason.nvim" = "1.10.0"
"fidget.nvim" = "1.4.1"
"conform.nvim" = "6.0.0"
nvim-lint = "scm"
"mason-lspconfig.nvim" = "1.29.0"

# Completion
luasnip = "2.3.0"
friendly-snippets = "scm"
nvim-cmp = "0.0.1"
cmp-nvim-lsp = "scm"
cmp-path = "scm"
cmp-buffer = "scm"
cmp_luasnip = "scm"
cmp-cmdline = "scm"

# Treesitter
nvim-treesitter-legacy-api = "0.9.2"
nvim-treesitter-textobjects = "scm"
nvim-treesitter-context = "scm"
tree-sitter-clojure = "scm"
tree-sitter-lua = "scm"

[bundles.init]
items = [
		"which-key.nvim",
		"gitsigns.nvim",
		"lualine.nvim",
		"toggleterm.nvim",
		"nvim-surround",
		"indent-blankline.nvim",
		"comment.nvim",
		"eyeliner.nvim"
]

[bundles.telescope]
items = [
		"telescope.nvim",
		"telescope-ui-select.nvim",
		"telescope-fzf-native.nvim"
]

[bundles.lsp]
items = [
		"nvim-lspconfig",
		"mason.nvim",
		"fidget.nvim",
		"conform.nvim",
		"nvim-lint",
		"mason-lspconfig.nvim",
]

[bundles.completions]
items = [
		"luasnip",
		"friendly-snippets",
		"nvim-cmp",
		"cmp-nvim-lsp",
		"cmp-path",
		"cmp-buffer",
		"cmp_luasnip",
		"cmp-cmdline"
]

[bundles.treesitter]
items = [
		"nvim-treesitter-legacy-api",
		"nvim-treesitter-textobjects",
		"nvim-treesitter-context"
]

[config]
plugin_dir = "plugins/"
auto_setup = false
