#!/usr/bin/env bash
case $- in
    *i*) ;; # interactive sesh
      *) return;; # non-interactive sesh, will break scp and sftp
esac

complete -Ef # so wsl doesn't die on empty completion

font_reset="$(tput sgr0)"
font_bold="$(tput bold)"
font_underline="$(tput smul)"
font_black="$(tput setaf 0)"
font_red="$(tput setaf 1)"
font_green="$(tput setaf 2)"
font_cyan="$(tput setaf 6)"
bg_yellow="$(tput setab 3)"

if command -v carapace &>/dev/null; then
  source <(carapace _carapace bash)
fi

if command -v starship &>/dev/null; then 
  eval "$(starship init bash)"
fi

if command -v eza &>/dev/null; then
  alias ls=eza
fi

if command -v zoxide &>/dev/null; then
  eval "$(zoxide init bash)"
  alias cd=z
  alias cdi=zi
fi

if command -v xpkg &>/dev/null; then
  alias xrm="sudo xbps-remove"
  xs() {
    xpkg -a | fzf -m --preview 'xq {1}' --preview-window=right:66%:wrap | xargs -ro xi
  }
fi

if command -v kubectl &>/dev/null; then
  alias k=kubectl
fi

if command -v bat &>/dev/null; then
  manless() {
    for cmd in "$@"; do
      man "$cmd"
    done | sed -u -e "s/\\x1B\[[0-9;]*m//g; s/.\\x08//g" | bat -p -l man
  }
else
  manless() {
    LESS_TERMCAP_mb="${font_bold}${font_green}" \
    LESS_TERMCAP_md="${font_bold}${font_cyan}" \
    LESS_TERMCAP_me="${font_reset}" \
    LESS_TERMCAP_se="${font_reset}" \
    LESS_TERMCAP_ue="${font_reset}" \
    LESS_TERMCAP_so="${font_black}${bg_yellow}" \
    LESS_TERMCAP_us="${font_underline}${font_red}" \
    LESSOPEN='|man %s' less -is "$@"
  }
fi

if command -v nvim &>/dev/null; then
  alias v="nvim"
  export MANPAGER="nvim +Man!"
elif command -v vim &>/dev/null; then
  export MANPAGER="vim +MANPAGER"
fi

if command -v chezmoi &>/dev/null; then
  alias che="chezmoi edit"
  alias chu="chezmoi update"
  alias cha="chezmoi apply"
  alias chr="chezmoi re-add"
  alias chc="chezmoi cd"
fi

if command -v git &>/dev/null; then
  alias ga="git add"
  alias gp="git push"
  alias gP="git pull"

  alias gc="git commit"
  alias gA="git commit --amend --no-edit"

  alias gf="git fetch"
  alias gco="git switch"

  alias gs="git status"
  alias gd="git diff"
  alias gD="git diff --staged"

  alias gr="git reset"
  alias gR="git reset --hard"

  alias gC="git cherry-pick"
  alias gB="git rebase"
  alias gM="git merge"

  alias gm="git push -u origin HEAD"
fi

bash_fzf=/usr/share/fzf/key-bindings.bash
if [ -f "$bash_fzf" ]; then 
  export FZF_ALT_C_COMMAND="fd -HL --type d"
  export FZF_ALT_C_OPTS="--preview 'tree {}'"
  source "$bash_fzf"
fi

take() {
  mkdir "$1"
  cd "$1"
}
