[font]
normal = { family = "JetBrainsMonoNerdFont" }
size = 10

[colors.primary]
background = "#272e33"
foreground = "#d3c6aa"

[colors.normal]
black = "#414b50"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"

[colors.bright]
black = "#475258"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"

[[hints.enabled]]
action = "Copy"
post_processing = true
persist = false
binding = { key = "Y", mods = "Control|Shift" }
mouse.enabled = true
regex = "[0-9a-f]{7,40}"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

